spring:
  application:
    name: CLINES-API
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:clines}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

cors:
  allowed:
    host: ${CORS_HOST:http://localhost:3000}